### ISSUE TITLE
You don't have "break" in you switches

### ISSUE THREAD

**Issue by gitfu** [foolip/608.js#5]
you are supposed to call break after every case statement, 
I believe if you add breaks your stuff will speed up, 
the switch statement will continue to process any remaining cases 
even after a match without breaks.

**Comment by foolip** [comment]
AFAICT, in every single case there's a return statement. Adding a break after that would be redundant &ndash; anything at all after the return statement would be unreachable dead code.

**Comment by gitfu** [comment]
I see your point,  and it makes sense. ...-------- Original Message --------Subject: Re: [608.js] You don't have "break" in you switches (#5)From: Philip Jägenstedt To: "foolip/608.js" 608.js@noreply.github.comCC: yeah AFAICT, in every single case there's a return statement. Adding a break after that would be redundant – anything at all after the return statement would be unreachable dead code.
